### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by anwarnunez** [anwarnunez/setup_files#1]
Ton of issues here

- [ ] tuples 4life
- [x] #2

> lisp, amirite?

- [ ] 

> 

- [ ] dicts 4life

> list are dicts bruv

**Comment by mazer-ai** [comment]
say what?

**Comment by anwarnunez** [comment]
car, cdr, cons!

**Comment by mazer-ai** [comment]
yeah -- but what's the issue refering to? did I use cdr/car in the code
somewhere?
